#include <ButtonConstants.au3>
#include <ComboConstants.au3>
#include <EditConstants.au3>
#include <GUIConstantsEx.au3>
#include <StaticConstants.au3>
#include <TabConstants.au3>
#include <WindowsConstants.au3>
Opt("GUIOnEventMode", 1)
#Region ### START Koda GUI section ### Form=D:\LapTrinh\AutoIT\SaiAL2\Sai AL2.kxf
$MainGUI = GUICreate("Sai AL2 v1.0 | 72ls.NET", 218, 129, 293, 250, -1, BitOR($WS_EX_TOPMOST,$WS_EX_WINDOWEDGE))
GUISetOnEvent($GUI_EVENT_CLOSE, "MainGUIClose")
$Tab1 = GUICtrlCreateTab(-1, -3, 227, 105)
$Login = GUICtrlCreateTabItem("Login")
GUICtrlSetState(-1,$GUI_SHOW)
$Label1 = GUICtrlCreateLabel("User:", 3, 25, 29, 17, 0)
$Account_CB = GUICtrlCreateCombo("", 37, 22, 113, 25, BitOR($CBS_DROPDOWN,$CBS_AUTOHSCROLL))
GUICtrlSetOnEvent(-1, "Account_CBChange")
$Password_L = GUICtrlCreateLabel("Pass:", 3, 49, 30, 17, 0)
GUICtrlSetCursor (-1, 0)
GUICtrlSetOnEvent(-1, "Password_LClick")
$Password_I = GUICtrlCreateInput("", 37, 46, 113, 21, BitOR($GUI_SS_DEFAULT_INPUT,$ES_PASSWORD))
$Login_B = GUICtrlCreateButton("Login", 155, 29, 59, 33, $BS_NOTIFY)
GUICtrlSetFont(-1, 12, 800, 0, "MS Sans Serif")
GUICtrlSetOnEvent(-1, "Login_BClick")
$Save_B = GUICtrlCreateButton("Save", 99, 75, 43, 17, $BS_NOTIFY)
GUICtrlSetOnEvent(-1, "Save_BClick")
$Load_B = GUICtrlCreateButton("Load", 51, 75, 43, 17, $BS_NOTIFY)
GUICtrlSetOnEvent(-1, "Load_BClick")
$Run_B = GUICtrlCreateButton("Run Game", 148, 75, 67, 17, $BS_NOTIFY)
GUICtrlSetOnEvent(-1, "Run_BClick")
$Delete_B = GUICtrlCreateButton("Delete", 4, 75, 43, 17, $BS_NOTIFY)
GUICtrlSetOnEvent(-1, "Delete_BClick")
$TabSheet1 = GUICtrlCreateTabItem("Search")
$Type_Co = GUICtrlCreateCombo("Monsters", 40, 49, 81, 25, BitOR($CBS_DROPDOWN,$CBS_AUTOHSCROLL))
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlSetOnEvent(-1, "Type_CoChange")
$Seach_B = GUICtrlCreateButton("Seach", 136, 49, 67, 21, $BS_NOTIFY)
GUICtrlSetOnEvent(-1, "Seach_BClick")
$Label2 = GUICtrlCreateLabel("Type:", 8, 51, 31, 17, 0)
$Label3 = GUICtrlCreateLabel("Key:", 14, 24, 25, 17, 0)
$Key_I = GUICtrlCreateCombo("Key_I", 40, 22, 145, 25, BitOR($CBS_DROPDOWN,$CBS_AUTOHSCROLL))
GUICtrlSetOnEvent(-1, "Key_IChange")
$DeleteKey_B = GUICtrlCreateButton("X", 189, 21, 25, 22, $BS_NOTIFY)
GUICtrlSetOnEvent(-1, "DeleteKey_BClick")
$GameList_Co = GUICtrlCreateCombo("", 40, 74, 145, 25, BitOR($CBS_DROPDOWNLIST,$CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "No Game", "No Game")
GUICtrlSetOnEvent(-1, "GameList_CoChange")
$Label4 = GUICtrlCreateLabel("Game:", 4, 76, 35, 17, 0)
$Reload_B = GUICtrlCreateButton("R", 189, 74, 25, 22, $BS_NOTIFY)
GUICtrlSetOnEvent(-1, "Reload_BClick")
$TabSheet2 = GUICtrlCreateTabItem("Option")
$KillGame_B = GUICtrlCreateButton("Kill Game", 136, 24, 67, 17, $BS_NOTIFY)
GUICtrlSetOnEvent(-1, "KillGame_BClick")
$GamePathSet_B = GUICtrlCreateButton("Game Path", 136, 48, 67, 17, $BS_NOTIFY)
GUICtrlSetOnEvent(-1, "GamePathSet_BClick")
$HomePage_B = GUICtrlCreateButton("Home Page", 136, 79, 67, 17, $BS_NOTIFY)
GUICtrlSetOnEvent(-1, "HomePage_BClick")
$AutoEnchant = GUICtrlCreateButton("Enchant", 16, 40, 67, 25)
GUICtrlSetOnEvent(-1, "AutoEnchantClick")
GUICtrlCreateTabItem("")
$Hidden_B = GUICtrlCreateButton("/\", 188, 104, 27, 20, $BS_NOTIFY)
GUICtrlSetOnEvent(-1, "Hidden_BClick")
$Waring_L = GUICtrlCreateLabel("72ls.NET is a LeeSai's Web ................", 2, 105, 187, 17, 0)
#EndRegion ### END Koda GUI section ###
