#include-once
#include "LNotice.au3"
#include "LCharList.au3"
#include "LIsTarget.au3"
#include "LMobHPCur.au3"
#include "LGameList.au3"
#include "LAddressEdit.au3"
#include "LFishing.au3"

#include "LTargetKey.au3"
#include "LFishingKey.au3"
#include "LPumpKey.au3"
#include "LReelKey.au3"

#include "LSkill1Key.au3"
#include "LSkill2Key.au3"
#include "LSkill3Key.au3"
#include "LSkill4Key.au3"
#include "LSkill5Key.au3"
#include "LSkill6Key.au3"
#include "LSkill7Key.au3"
#include "LSkill8Key.au3"
#include "LSkill9Key.au3"
#include "LSkill10Key.au3"

#include "LSkill101Key.au3"
#include "LSkill102Key.au3"
#include "LSkill103Key.au3"
#include "LSkill104Key.au3"
#include "LSkill105Key.au3"
#include "LSkill106Key.au3"
#include "LSkill107Key.au3"
#include "LSkill108Key.au3"
#include "LSkill109Key.au3"
#include "LSkill110Key.au3"

#include "LSkill1Delay.au3"
#include "LSkill2Delay.au3"
#include "LSkill3Delay.au3"
#include "LSkill4Delay.au3"
#include "LSkill5Delay.au3"
#include "LSkill6Delay.au3"
#include "LSkill7Delay.au3"
#include "LSkill8Delay.au3"
#include "LSkill9Delay.au3"
#include "LSkill10Delay.au3"

#include "LSkill101Delay.au3"
#include "LSkill102Delay.au3"
#include "LSkill103Delay.au3"
#include "LSkill104Delay.au3"
#include "LSkill105Delay.au3"
#include "LSkill106Delay.au3"
#include "LSkill107Delay.au3"
#include "LSkill108Delay.au3"
#include "LSkill109Delay.au3"
#include "LSkill110Delay.au3"