<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="vi" xml:lang="vi">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
<meta http-equiv="content-language" content="vi"/>
<meta name="resource-type" content="document"/>
<meta name="description" content=""/>
<link rel="stylesheet" type="text/css" href="./include/style.css" />
<title><?php echo $page_title; ?></title>
</head>
<body>
<table border=0 cellspacing=0 cellpadding=0 class=page>
<tr><td>
<h2 align=center>Bắn Tàu Chiến Online</h2>
<tr><td>
	<table border=1 cellspacing=0 cellpadding=0 align=center>
	<tr><td class=menustyle align=center><a href="./">Trang Chủ</a>
		<td class=menustyle align=center><a href="./ucp.php?mode=register">Đăng Ký</a>
		<td class=menustyle align=center><a href="./ucp.php?mode=user">Thành Viên</a>
	</table>
	<hr>
<tr><td align=center>