<form action="./ucp.php?mode=register" method=post>
	<table border=0>
		<th colspan=2>Đăng Ký Tài Khoản
		<tr><td>Tên đăng nhập <td>: <input type=text name=name />		
		<tr><td>Mật khẩu <td>: <input type=password name=pass />
		<tr><td>Nhập lại mật khẩu <td>: <input type=password name=repass />
		<tr><td>Email <td>: <input type=text name=email>
		<tr><td><td>* Bạn nên sử dụng tài khoản email thật để đăng ký.
		<tr><td><td><input type=submit name=submit value="Đăng Ký" />
	</table>
</form>