#include <ButtonConstants.au3>
#include <ComboConstants.au3>
#include <GUIConstantsEx.au3>
#include <StaticConstants.au3>
#include <TabConstants.au3>
#include <WindowsConstants.au3>
Opt("GUIOnEventMode", 1)
#Region ### START Koda GUI section ### Form=F:\Lap Trinh\AutoIT\Develop\aSudoku\aSudoku.kxf
$MainGUI = GUICreate("Sai GUI v1.0 | 72ls.NET", 162, 152, 398, 154, BitOR($WS_SYSMENU,$WS_CAPTION,$WS_POPUP,$WS_POPUPWINDOW,$WS_BORDER,$WS_CLIPSIBLINGS), $WS_EX_TOPMOST)
GUISetOnEvent($GUI_EVENT_CLOSE, "MainGUIClose")
$Hidden_B = GUICtrlCreateButton("/\", 132, 128, 27, 20, 0)
GUICtrlSetOnEvent(-1, "Hidden_BClick")
$Waring_L = GUICtrlCreateLabel("72ls.NET is a LeeSai's Web.......", 1, 109, 157, 17)
$HomePage_B = GUICtrlCreateButton("?", 101, 128, 27, 20, 0)
GUICtrlSetOnEvent(-1, "HomePage_BClick")
$Mode_Co = GUICtrlCreateCombo("", 4, 128, 41, 25, BitOR($CBS_DROPDOWNLIST,$CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "4|6|9|16", "9")
GUICtrlSetTip(-1, "Type")
GUICtrlSetOnEvent(-1, "Mode_CoChange")
$Tab1 = GUICtrlCreateTab(0, 0, 161, 105)
GUICtrlSetResizing(-1, $GUI_DOCKWIDTH+$GUI_DOCKHEIGHT)
$TabSheet1 = GUICtrlCreateTabItem("Create")
$Create_B = GUICtrlCreateButton("Create New", 8, 28, 75, 20, 0)
GUICtrlSetOnEvent(-1, "Create_BClick")
$Save_B = GUICtrlCreateButton("Save", 96, 28, 59, 20, 0)
GUICtrlSetOnEvent(-1, "Save_BClick")
$Reset_B = GUICtrlCreateButton("Reset", 112, 60, 43, 20, 0)
GUICtrlSetOnEvent(-1, "Reset_BClick")
$Remove_B = GUICtrlCreateButton("Remove Number", 8, 60, 91, 20, 0)
GUICtrlSetOnEvent(-1, "Remove_BClick")
$TabSheet2 = GUICtrlCreateTabItem("Software")
GUICtrlSetState(-1,$GUI_SHOW)
$SoftSudokuGetB = GUICtrlCreateButton("Get Sudoku", 8, 28, 75, 20, 0)
GUICtrlSetOnEvent(-1, "SoftSudokuGetBClick")
$SoftPathB = GUICtrlCreateButton("Get Path", 96, 28, 59, 20, 0)
GUICtrlSetOnEvent(-1, "SoftPathBClick")
$SoftListCo = GUICtrlCreateCombo("", 58, 52, 97, 25, BitOR($CBS_DROPDOWNLIST,$CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "mtSudoku", "mtSudoku")
GUICtrlSetOnEvent(-1, "SoftListCoChange")
$SoftRunB = GUICtrlCreateButton("Run", 8, 52, 43, 20, 0)
GUICtrlSetOnEvent(-1, "SoftRunBClick")
$SoftLevelB = GUICtrlCreateCombo("", 114, 77, 41, 25, BitOR($CBS_DROPDOWNLIST,$CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "1|2|3|4|5|6|7", "3")
GUICtrlSetTip(-1, "Soft Level")
GUICtrlSetOnEvent(-1, "SoftLevelBChange")
GUICtrlCreateTabItem("")
$LevelCo = GUICtrlCreateCombo("", 51, 128, 41, 25, BitOR($CBS_DROPDOWNLIST,$CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "1|2|3|4|5|6|7", "3")
GUICtrlSetTip(-1, "Level")
GUICtrlSetOnEvent(-1, "LevelCoChange")
#EndRegion ### END Koda GUI section ###
