#include <ButtonConstants.au3>
#include <ComboConstants.au3>
#include <EditConstants.au3>
#include <GUIConstantsEx.au3>
#include <StaticConstants.au3>
#include <WindowsConstants.au3>
Opt("GUIOnEventMode", 1)
#Region ### START Koda GUI section ### Form=C:\Duc\Dropbox\KMCabal\Data\adReader\adReader.kxf
$MainGUI = GUICreate("SaiGUI", 294, 167, 218, 140, -1, BitOR($WS_EX_TOOLWINDOW,$WS_EX_TOPMOST,$WS_EX_WINDOWEDGE))
GUISetOnEvent($GUI_EVENT_CLOSE, "FAutoEnd")
$BHidden = GUICtrlCreateButton("/\", 260, 136, 27, 25, $BS_NOTIFY)
GUICtrlSetTip(-1, "Minimize Tool")
GUICtrlSetOnEvent(-1, "BHiddenClick")
$LNotice = GUICtrlCreateLabel("Notice...", 10, 144, 44, 17, $SS_LEFTNOWORDWRAP)
$BHomePage = GUICtrlCreateButton("?", 229, 136, 27, 25, $BS_NOTIFY)
GUICtrlSetOnEvent(-1, "BHomePageClick")
$Label1 = GUICtrlCreateLabel("Process List:", 8, 10, 64, 17, 0)
$CBProcessList = GUICtrlCreateCombo("", 72, 8, 129, 25, BitOR($CBS_DROPDOWNLIST,$CBS_AUTOHSCROLL))
GUICtrlSetOnEvent(-1, "CBProcessListChange")
$BProcessOpen = GUICtrlCreateButton("Open", 216, 6, 67, 25, $BS_NOTIFY)
GUICtrlSetOnEvent(-1, "BProcessOpenClick")
$LAddress = GUICtrlCreateLabel("Address:", 8, 74, 53, 17, 0)
GUICtrlSetFont(-1, 8, 800, 0, "MS Sans Serif")
GUICtrlSetColor(-1, 0x0000FF)
GUICtrlSetTip(-1, "Click here to change Address type")
GUICtrlSetCursor (-1, 0)
GUICtrlSetOnEvent(-1, "LAddressClick")
$IAddressStart = GUICtrlCreateInput("IAddressStart", 72, 72, 129, 21, $GUI_SS_DEFAULT_INPUT)
GUICtrlSetOnEvent(-1, "IAddressStartChange")
$IAddressSpan = GUICtrlCreateInput("20", 152, 105, 49, 21, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER))
GUICtrlSetOnEvent(-1, "IAddressSpanChange")
$IOffset = GUICtrlCreateInput("4", 48, 105, 49, 21, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER))
GUICtrlSetOnEvent(-1, "IOffsetChange")
$Label3 = GUICtrlCreateLabel("Offset:", 8, 107, 35, 17, 0)
$Label4 = GUICtrlCreateLabel("Span:", 114, 107, 32, 17, 0)
$Label5 = GUICtrlCreateLabel("Review:", 8, 40, 43, 17, 0)
$IAddressReview = GUICtrlCreateInput("IAddressReview", 72, 38, 129, 21, $GUI_SS_DEFAULT_INPUT)
GUICtrlSetOnEvent(-1, "IAddressReviewChange")
$LReviewValue = GUICtrlCreateLabel("0000000000000", 208, 43, 82, 17, $SS_CENTER)
GUICtrlSetOnEvent(-1, "LReviewValueClick")
$CBAddType = GUICtrlCreateCombo("", 218, 72, 65, 25, BitOR($CBS_DROPDOWNLIST,$CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "char[32]|wchar[32]|dword|float|double", "dword")
GUICtrlSetOnEvent(-1, "CBAddTypeChange")
$Button1 = GUICtrlCreateButton("Save", 216, 104, 67, 25)
$BNextSpan = GUICtrlCreateButton(">>", 160, 136, 43, 25)
GUICtrlSetTip(-1, "Current Address + Span")
GUICtrlSetOnEvent(-1, "BNextSpanClick")
$BBackSpan = GUICtrlCreateButton("<<", 96, 136, 43, 25)
GUICtrlSetTip(-1, "Current Address - Span")
GUICtrlSetOnEvent(-1, "BBackSpanClick")
#EndRegion ### END Koda GUI section ###